name: "first-workflow"

on: 
  push:
    branches: 
      - main
env:
  colourname: red
  textname: 'Ship it!!!!!'
  
jobs:
  
  Job1:
    runs-on: ubuntu-latest
    steps:
    - name: job1
      run: echo "step1 and step2 as applicable"
      
  Job2:
    runs-on: ubuntu-latest
    needs: [Job1]
    steps:  
    - name: Cowsays
        # You may pin to the exact commit or the version.
        # uses: mscoutermarsh/cowsays-action@822c8424f7ebc1f4c8b86b0bcb11e4051b7f42e2
      uses: mscoutermarsh/cowsays-action@v1
      with:
    # What does the cow say?
        text: hello world 
        color: red
    # optional, default is Ship it!!!!!
    # Color of your cow
    #color:'red' # optional, default is white
